name:                msweeper
version:             0.1.0.0
github:              "proelbtn/msweeper"
license:             ""
author:              "proelbtn"
maintainer:          "proelbtn@users.noreply.github.com"
copyright:           ""

extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - msweeper

tests:
  test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - msweeper
